version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
jobs:
  build:
    docker:
      - image: circleci/node:16.13
    working_directory: ~/repo
    steps:
      - checkout
      # install dependencies
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run tests
          command: yarn build
      - run:
          name: Add dist
          command: echo "\!dist/**/*" >> .gitignore
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .gitignore
            - package.json
   deploy-job:
      working_directory: ~/repo
      docker: 
         - image: circleci/node:12.18.2
      steps:
         - attach_workspace:
            at: ~/repo
         - heroku/deploy-via-git:
            force: true

workflows:
  heroku_deploy:
    jobs:
      - build
      - deploy-job: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: main
